import { Inter } from "@next/font/google";
import Head from "next/head";
import { useState } from "react";
import Form from "../components/Form";
import Table from "../components/Table";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [visible, setVisible] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <h2 className="text-xl md:text-5xl text-center font-semibold p-10">
          Employee Management
        </h2>
        <div className="mb-6">
          <button
            onClick={() => setVisible(!visible)}
            className="bg-indigo-500 py-2 items-center flex gap-1 hover:bg-indigo-600 transition duration-300 text-white rounded px-4"
          >
            <span>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="w-5 h-5"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M19 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 11-6.75 0 3.375 3.375 0 016.75 0zM4 19.235v-.11a6.375 6.375 0 0112.75 0v.109A12.318 12.318 0 0110.374 21c-2.331 0-4.512-.645-6.374-1.766z"
                />
              </svg>
            </span>{" "}
            Add Employee
          </button>
        </div>
      </div>
      {/* form */}
      <div className="container mx-auto">{visible && <Form />}</div>
      {/* table */}
      <div className="container mx-auto">
        <Table />
      </div>
    </>
  );
}
